"""
Portfolio Account Module.

This module manages the account and position state for the event-driven backtesting
framework. It tracks cash balance, equity, positions, margin, and P&L.
It supports both long and short positions, margin/leverage adjustments,
average cost basis tracking, and transaction logging.
"""

import logging
from dataclasses import dataclass, field
from typing import Dict, Optional

# Setup logger for the module
logger = logging.getLogger("portfolio.account")
if not logger.handlers:
    handler = logging.StreamHandler()
    formatter = logging.Formatter(
        "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    )
    handler.setFormatter(formatter)
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)


@dataclass
class Position:
    """
    Represents an active trading position in a specific asset.

    Attributes:
        ticker: The asset symbol.
        quantity: The signed quantity of the position (positive for LONG, negative for SHORT).
        avg_price: The average entry price of the position.
        current_price: The current market price of the asset (for mark-to-market).
        multiplier: Contract size multiplier (default 1.0).
    """

    ticker: str
    quantity: float = 0.0
    avg_price: float = 0.0
    current_price: float = 0.0
    multiplier: float = 1.0

    @property
    def direction(self) -> str:
        """Returns 'LONG', 'SHORT', or 'FLAT' depending on position quantity."""
        if self.quantity > 0:
            return "LONG"
        elif self.quantity < 0:
            return "SHORT"
        return "FLAT"

    @property
    def unrealized_pnl(self) -> float:
        """
        Calculates unrealized profit and loss.
        Formula: (current_price - avg_price) * quantity * multiplier
        This holds mathematically for both LONG and SHORT positions because
        quantity is negative for SHORT.
        """
        return (self.current_price - self.avg_price) * self.quantity * self.multiplier

    @property
    def market_value(self) -> float:
        """
        Calculates the gross exposure / asset value of the position.
        Formula: |quantity * current_price * multiplier|
        """
        return abs(self.quantity * self.current_price * self.multiplier)

    def update_position(self, fill_qty: float, fill_price: float) -> float:
        """
        Updates the position with a new execution fill.
        Uses average cost accounting to update position size and average price.
        Returns the realized PnL generated by this transaction.

        Args:
            fill_qty: Signed quantity of the fill (positive = BUY, negative = SELL).
            fill_price: The execution price of the fill.
        """
        q_old = self.quantity
        q_fill = fill_qty
        q_new = q_old + q_fill

        realized_pnl = 0.0

        if q_old == 0:
            # 1. Opening a new position from FLAT
            self.avg_price = fill_price
            self.quantity = q_new
            logger.info(
                f"[{self.ticker}] Opened {self.direction} position: "
                f"Size = {abs(q_new)}, Price = {fill_price:.2f}"
            )
        elif (q_old > 0 and q_new >= 0) or (q_old < 0 and q_new <= 0):
            # 2. Adding to or reducing position without crossing FLAT
            if abs(q_new) > abs(q_old):
                # Adding to position: Update average price
                self.avg_price = (q_old * self.avg_price + q_fill * fill_price) / q_new
                logger.info(
                    f"[{self.ticker}] Added to {self.direction} position: "
                    f"Added Size = {abs(q_fill)}, New Size = {abs(q_new)}, "
                    f"New Avg Price = {self.avg_price:.2f}"
                )
            else:
                # Reducing or closing position: Realize P&L, avg_price stays constant
                realized_pnl = -q_fill * (fill_price - self.avg_price) * self.multiplier
                logger.info(
                    f"[{self.ticker}] Reduced {self.direction} position: "
                    f"Reduced Size = {abs(q_fill)}, Remaining Size = {abs(q_new)}, "
                    f"Realized P&L = {realized_pnl:.2f}"
                )
            self.quantity = q_new
        else:
            # 3. Position Reversal (crossing FLAT from LONG to SHORT or vice versa)
            q_close = -q_old
            q_open = q_new
            # Realize PnL on the closing portion
            realized_pnl = -q_close * (fill_price - self.avg_price) * self.multiplier
            # Set up the new reversed position
            old_direction = self.direction
            self.avg_price = fill_price
            self.quantity = q_open
            logger.info(
                f"[{self.ticker}] Reversed position from {old_direction} to {self.direction}: "
                f"Closed = {abs(q_close)}, Opened = {abs(q_open)}, "
                f"Realized P&L = {realized_pnl:.2f}, New Avg Price = {fill_price:.2f}"
            )

        self.current_price = fill_price  # Mark to market at fill price
        return realized_pnl


class Account:
    """
    Manages the overall trading account state, including capital, positions,
    and leverage tracking.

    Attributes:
        initial_capital: The starting capital of the account.
        margin_requirement: Margin required as fraction of exposure (e.g. 1.0 for Spot, 0.05 for 20x leverage).
    """

    def __init__(self, initial_capital: float, margin_requirement: float = 1.0) -> None:
        self.initial_capital: float = initial_capital
        self.balance: float = initial_capital  # Realized capital (cash + realized PnL - commissions)
        self.margin_requirement: float = margin_requirement
        self.positions: Dict[str, Position] = {}
        self.total_commission: float = 0.0
        self.total_realized_pnl: float = 0.0

        logger.info(
            f"Account initialized with Initial Capital = {initial_capital:.2f}, "
            f"Margin Requirement = {margin_requirement * 100:.1f}%"
        )

    @property
    def cash(self) -> float:
        """Alias for balance."""
        return self.balance

    @property
    def unrealized_pnl(self) -> float:
        """Sum of unrealized P&L across all open positions."""
        return sum(pos.unrealized_pnl for pos in self.positions.values())

    @property
    def equity(self) -> float:
        """Total account value (Realized Balance + Unrealized P&L)."""
        return self.balance + self.unrealized_pnl

    @property
    def used_margin(self) -> float:
        """Total margin currently locked in active positions."""
        return sum(pos.market_value * self.margin_requirement for pos in self.positions.values())

    @property
    def free_margin(self) -> float:
        """Remaining margin available to open new positions."""
        return self.equity - self.used_margin

    @property
    def margin_level(self) -> float:
        """
        Account margin level percentage.
        Formula: (Equity / Used Margin) * 100
        Returns infinity if no margin is currently used.
        """
        if self.used_margin == 0:
            return float("inf")
        return (self.equity / self.used_margin) * 100

    @property
    def is_margin_called(self) -> bool:
        """
        Flags if the account has entered a margin call state.
        Triggers if Equity drops below the required Used Margin (or Equity <= 0).
        """
        return self.equity < self.used_margin or self.equity <= 0

    def update_market_price(self, ticker: str, price: float) -> None:
        """
        Updates the current market price of an asset to mark-to-market.

        Args:
            ticker: The asset symbol.
            price: The new market price.
        """
        if ticker in self.positions:
            pos = self.positions[ticker]
            pos.current_price = price
            # Log warnings if critical state is reached
            if self.is_margin_called:
                logger.warning(
                    f"MARGIN CALL WARNING: Ticker {ticker} price moved to {price:.2f}. "
                    f"Equity: {self.equity:.2f}, Used Margin: {self.used_margin:.2f}"
                )

    def apply_fill(
        self,
        ticker: str,
        action: str,
        quantity: float,
        price: float,
        commission: float,
        multiplier: float = 1.0,
    ) -> bool:
        """
        Applies an execution fill to the account. Updates positions, P&L,
        and cash balance.

        Args:
            ticker: The asset symbol.
            action: Execution action ('BUY' or 'SELL').
            quantity: Absolute quantity filled (must be positive).
            price: Execution price.
            commission: Transaction fee/commission.
            multiplier: Contract size multiplier.

        Returns:
            bool: True if fill was applied successfully, False otherwise.
        """
        if quantity <= 0:
            logger.error(f"Invalid fill quantity for {ticker}: {quantity}. Must be > 0.")
            return False

        action_upper = action.upper()
        if action_upper == "BUY":
            fill_qty = quantity
        elif action_upper == "SELL":
            fill_qty = -quantity
        else:
            logger.error(f"Invalid execution action for {ticker}: {action}. Must be 'BUY' or 'SELL'.")
            return False

        logger.info(
            f"Applying fill: {action_upper} {quantity} {ticker} @ {price:.2f}, "
            f"Commission = {commission:.2f}"
        )

        # Initialize position if not exists
        if ticker not in self.positions:
            self.positions[ticker] = Position(ticker=ticker, multiplier=multiplier)

        pos = self.positions[ticker]

        # Apply transaction to the position
        realized_pnl = pos.update_position(fill_qty, price)

        # Update account balances
        self.total_commission += commission
        self.total_realized_pnl += realized_pnl
        self.balance += realized_pnl - commission

        # Clean up flat positions to save memory
        if pos.quantity == 0:
            logger.info(f"[{ticker}] Position closed/flat. Removing from active positions list.")
            del self.positions[ticker]

        logger.info(
            f"Account State -> Equity: {self.equity:.2f}, Balance/Cash: {self.balance:.2f}, "
            f"Free Margin: {self.free_margin:.2f}"
        )

        return True


# ==============================================================================
# Unit Tests
# ==============================================================================


def test_position_long_calculations():
    """Test standard LONG position calculations and status transitions."""
    pos = Position(ticker="AAPL", quantity=10, avg_price=100.0, current_price=100.0)
    assert pos.direction == "LONG"
    assert pos.unrealized_pnl == 0.0
    assert pos.market_value == 1000.0

    pos.current_price = 110.0
    assert pos.unrealized_pnl == 100.0
    assert pos.market_value == 1100.0


def test_position_short_calculations():
    """Test standard SHORT position calculations and status transitions."""
    pos = Position(ticker="TSLA", quantity=-5, avg_price=200.0, current_price=200.0)
    assert pos.direction == "SHORT"
    assert pos.unrealized_pnl == 0.0
    assert pos.market_value == 1000.0

    pos.current_price = 180.0
    assert pos.unrealized_pnl == 100.0
    assert pos.market_value == 900.0


def test_position_average_cost_addition():
    """Test average cost calculation when buying more shares."""
    pos = Position(ticker="NVDA")
    # Buy 10 at 100
    pnl1 = pos.update_position(10, 100.0)
    assert pnl1 == 0.0
    assert pos.quantity == 10
    assert pos.avg_price == 100.0

    # Buy 10 more at 120
    pnl2 = pos.update_position(10, 120.0)
    assert pnl2 == 0.0
    assert pos.quantity == 20
    assert pos.avg_price == 110.0


def test_position_reduction_and_close():
    """Test position reduction, P&L realization, and closure."""
    pos = Position(ticker="MSFT")
    # Buy 10 at 300
    pos.update_position(10, 300.0)

    # Sell 4 at 320 (reduce long)
    pnl_reduction = pos.update_position(-4, 320.0)
    assert pnl_reduction == 80.0  # (320 - 300) * 4
    assert pos.quantity == 6
    assert pos.avg_price == 300.0  # Average price remains unchanged

    # Sell remaining 6 at 330 (close position)
    pnl_close = pos.update_position(-6, 330.0)
    assert pnl_close == 180.0  # (330 - 300) * 6
    assert pos.quantity == 0


def test_position_reversal():
    """Test reversing a position from LONG to SHORT and vice versa."""
    pos = Position(ticker="BTC")
    # Long 2 at 50,000
    pos.update_position(2, 50000.0)

    # Sell 5 at 55,000 (closes 2 long, opens 3 short)
    pnl_reverse = pos.update_position(-5, 55000.0)
    assert pnl_reverse == 10000.0  # (55000 - 50000) * 2
    assert pos.quantity == -3
    assert pos.avg_price == 55000.0
    assert pos.direction == "SHORT"


def test_account_calculations_spot():
    """Test account equity, balance, and margin tracking in a 100% margin (Spot) account."""
    acct = Account(initial_capital=10000.0, margin_requirement=1.0)
    assert acct.equity == 10000.0
    assert acct.cash == 10000.0
    assert acct.free_margin == 10000.0

    # Buy 50 AAPL at 100, commission = 10
    success = acct.apply_fill("AAPL", "BUY", 50, 100.0, 10.0)
    assert success
    assert acct.total_commission == 10.0
    assert acct.balance == 9990.0  # Cash balance only changes with commissions/realized P&L
    assert acct.used_margin == 5000.0  # 50 shares * 100 price * 1.0 margin
    assert acct.unrealized_pnl == 0.0
    assert acct.equity == 9990.0
    assert acct.free_margin == 4990.0

    # Price increases to 110
    acct.update_market_price("AAPL", 110.0)
    assert acct.unrealized_pnl == 500.0  # (110 - 100) * 50
    assert acct.equity == 10490.0  # 9990 + 500
    assert acct.used_margin == 5500.0  # 50 * 110 * 1.0
    assert acct.free_margin == 4990.0

    # Sell 50 AAPL at 110, commission = 10
    acct.apply_fill("AAPL", "SELL", 50, 110.0, 10.0)
    assert acct.total_realized_pnl == 500.0
    assert acct.balance == 10480.0  # 9990 + 500 realized - 10 commission
    assert acct.equity == 10480.0
    assert acct.used_margin == 0.0
    assert acct.free_margin == 10480.0
    assert "AAPL" not in acct.positions


def test_account_leverage_margin_call():
    """Test account leveraged buying and margin call detection."""
    # 10% Margin requirement (10x Leverage)
    acct = Account(initial_capital=1000.0, margin_requirement=0.1)

    # Buy 90 AAPL at 100, commission = 5
    acct.apply_fill("AAPL", "BUY", 90, 100.0, 5.0)
    assert acct.balance == 995.0
    assert acct.used_margin == 900.0  # 90 * 100 * 0.1
    assert acct.free_margin == 95.0  # 995 - 900
    assert not acct.is_margin_called

    # Price drops to 90
    acct.update_market_price("AAPL", 90.0)
    # Unrealized P&L = (90 - 100) * 90 = -900
    # Equity = 995 - 900 = 95
    # Used Margin = 90 * 90 * 0.1 = 810
    # Equity (95) < Used Margin (810) -> Margin Call!
    assert acct.is_margin_called


# ==============================================================================
# Usage Example
# ==============================================================================


def run_examples():
    """Demonstrates portfolio management usage examples with full logs."""
    print("--- Running Portfolio Backtest Account Example ---")
    # Initialize a leveraged trading account (e.g. 5x leverage / 20% margin requirement)
    account = Account(initial_capital=5000.0, margin_requirement=0.2)

    # 1. Open Long position on Ticker 'AAPL'
    account.apply_fill(ticker="AAPL", action="BUY", quantity=50, price=150.0, commission=15.0)

    # 2. Open Short position on Ticker 'BTC'
    account.apply_fill(ticker="BTC", action="SELL", quantity=0.1, price=60000.0, commission=5.0)

    # 3. Simulate market updates
    print("\nUpdating market prices...")
    account.update_market_price(ticker="AAPL", price=155.0)  # AAPL goes up (gaining on long)
    account.update_market_price(ticker="BTC", price=62000.0)  # BTC goes up (losing on short)

    # Print status
    print(f"Current Account Equity: ${account.equity:.2f}")
    print(f"Current Unrealized P&L: ${account.unrealized_pnl:.2f}")
    print(f"Used Margin: ${account.used_margin:.2f}")
    print(f"Free Margin: ${account.free_margin:.2f}")
    print(f"Margin Level: {account.margin_level:.1f}%")

    # 4. Close the BTC Short position (with loss)
    print("\nClosing short position on BTC...")
    account.apply_fill(ticker="BTC", action="BUY", quantity=0.1, price=62000.0, commission=5.0)

    # 5. Sell partial AAPL Long position (with profit)
    print("\nReducing long position on AAPL...")
    account.apply_fill(ticker="AAPL", action="SELL", quantity=25, price=160.0, commission=10.0)

    # Final Account State
    print(f"\nFinal Account Balance: ${account.balance:.2f}")
    print(f"Final Total Realized PnL: ${account.total_realized_pnl:.2f}")
    print(f"Final Total Commissions Paid: ${account.total_commission:.2f}")
    print(f"Remaining active positions: {list(account.positions.keys())}")


if __name__ == "__main__":
    # If run directly, run usage examples
    run_examples()
