"""
Portfolio Risk Engine Module.

This module implements a professional, event-driven Risk Engine.
It supports multiple pre-trade position sizing models:
- Risk Per Trade
- Fixed Position (quantity or capital)
- Kelly Criterion (fractional)
- Volatility Target
- ATR Position Sizing

And post-trade/real-time risk limits:
- Maximum Portfolio Risk
- Maximum Daily Loss
- Maximum Drawdown Stop
- Maximum Concurrent Positions
- Maximum Margin Usage

It also tracks and generates a detailed Risk Report.
"""

import logging
import math
from dataclasses import dataclass, field
from datetime import datetime, date
from typing import Dict, List, Optional, Any, Union

# Setup logger for the module
logger = logging.getLogger("portfolio.risk")
if not logger.handlers:
    handler = logging.StreamHandler()
    formatter = logging.Formatter(
        "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    )
    handler.setFormatter(formatter)
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)


@dataclass
class RiskParameters:
    """
    Configuration parameters for the RiskEngine.

    Attributes:
        sizing_mode: 'risk_per_trade', 'fixed_qty', 'fixed_capital', 'kelly', 'vol_target', 'atr'.
        fixed_qty: Position size in contracts if sizing_mode is 'fixed_qty'.
        fixed_capital: Capital in USDT to allocate per position if sizing_mode is 'fixed_capital'.
        risk_pct: Fraction of equity to risk per trade (e.g. 0.01 for 1%). Used in 'risk_per_trade' and 'atr'.
        kelly_fraction: Fraction of Kelly size to use (e.g. 0.5 for half-Kelly).
        target_vol_ann: Annualized target portfolio volatility (e.g. 0.15 for 15%).
        atr_multiplier: Multiplier applied to ATR for position sizing stop-loss distance.
        max_portfolio_risk_pct: Max sum of open position risks (stop-loss * size) as fraction of equity.
        max_daily_loss_pct: Max allowed daily loss as fraction of daily starting equity (e.g. 0.05 for 5%).
        max_drawdown_pct: Max peak-to-trough drawdown fraction to halt trading (e.g. 0.20 for 20%).
        max_concurrent_positions: Max number of active tickers in the portfolio.
        max_margin_usage_pct: Max total margin used as fraction of equity (e.g. 0.80 for 80%).
        leverage: Leverage factor used to compute margin requirements (e.g. 10.0 for 10x).
    """

    sizing_mode: str = "fixed_capital"
    fixed_qty: float = 1.0
    fixed_capital: float = 1000.0
    risk_pct: float = 0.01
    kelly_fraction: float = 0.5
    target_vol_ann: float = 0.15
    atr_multiplier: float = 2.0
    
    # Risk limits
    max_portfolio_risk_pct: float = 0.10
    max_daily_loss_pct: float = 0.05
    max_drawdown_pct: float = 0.20
    max_concurrent_positions: Optional[int] = None
    max_margin_usage_pct: float = 0.80
    leverage: float = 1.0


@dataclass
class RiskReport:
    """
    Performance and constraint validation report generated by the RiskEngine.
    """

    initial_equity: float
    ending_equity: float
    peak_equity: float
    max_drawdown_pct: float
    total_trades_evaluated: int
    trades_blocked: int
    block_reasons: Dict[str, int] = field(default_factory=dict)
    max_daily_loss_observed: float = 0.0
    max_margin_usage_observed: float = 0.0
    daily_pnl_history: Dict[str, float] = field(default_factory=dict)
    trading_halted: bool = False

    def print_summary(self) -> None:
        """Prints a human-readable summary of the risk report."""
        print("==================================================")
        print("               RISK ENGINE REPORT                 ")
        print("==================================================")
        print(f"Initial Equity:              ${self.initial_equity:,.2f}")
        print(f"Ending Equity:               ${self.ending_equity:,.2f}")
        print(f"Peak Equity:                 ${self.peak_equity:,.2f}")
        print(f"Max Drawdown:                {self.max_drawdown_pct * 100:.2f}%")
        print(f"Total Trades Evaluated:      {self.total_trades_evaluated}")
        print(f"Trades Blocked:              {self.trades_blocked}")
        print(f"Max Daily Loss Observed:     ${self.max_daily_loss_observed:,.2f}")
        print(f"Max Margin Usage Observed:   {self.max_margin_usage_observed * 100:.2f}%")
        print("--------------------------------------------------")
        print("Block Reasons:")
        for reason, count in self.block_reasons.items():
            print(f"  - {reason}: {count}")
        print("==================================================")


class RiskEngine:
    """
    Professional Risk Engine tracking sizing and real-time portfolio limits.
    """

    def __init__(self, params: RiskParameters) -> None:
        """
        Initializes the RiskEngine with the given parameters.
        """
        self.params = params
        self.reset()

    def reset(self) -> None:
        """Resets the internal tracking state of the RiskEngine."""
        self.peak_equity: float = 0.0
        self.current_drawdown: float = 0.0
        self.trading_halted: bool = False
        self.trades_evaluated: int = 0
        self.trades_blocked: int = 0
        self.block_reasons: Dict[str, int] = {
            "max_drawdown": 0,
            "max_daily_loss": 0,
            "max_concurrent_positions": 0,
            "max_margin_usage": 0,
            "max_portfolio_risk": 0,
        }
        self.max_daily_loss_observed: float = 0.0
        self.max_margin_usage_observed: float = 0.0

        # Daily tracking metrics
        self.current_day: Optional[date] = None
        self.daily_starting_equity: float = 0.0
        self.daily_pnl_history: Dict[str, float] = {}

    def calculate_position_size(
        self,
        equity: float,
        entry_price: float,
        stop_loss_dist: Optional[float] = None,
        stop_loss_pct: Optional[float] = None,
        win_rate: Optional[float] = None,
        win_loss_ratio: Optional[float] = None,
        asset_vol_ann: Optional[float] = None,
        atr: Optional[float] = None,
    ) -> float:
        """
        Calculates position size in contracts based on the configured sizing_mode.

        Args:
            equity: Current account equity.
            entry_price: Entry price of the asset.
            stop_loss_dist: Stop-loss distance in absolute price difference.
            stop_loss_pct: Stop-loss percentage (e.g. 0.05 for 5%).
            win_rate: Asset strategy historical win rate (0.0 to 1.0).
            win_loss_ratio: Average win size divided by average loss size.
            asset_vol_ann: Annualized historical standard deviation/volatility of the asset.
            atr: Average True Range (ATR) value for the asset.

        Returns:
            Calculated quantity of contracts (float). Returns 0.0 if parameters are insufficient.
        """
        if equity <= 0:
            logger.warning("Equity is <= 0. Cannot size position.")
            return 0.0

        if entry_price <= 0:
            logger.warning("Entry price is <= 0. Cannot size position.")
            return 0.0

        mode = self.params.sizing_mode.lower()

        if mode == "fixed_qty":
            return float(self.params.fixed_qty)

        elif mode == "fixed_capital":
            return self.params.fixed_capital / entry_price

        elif mode == "risk_per_trade":
            # Risk Capital = Equity * Risk %
            risk_cap = equity * self.params.risk_pct
            
            # Determine stop loss distance
            dist = 0.0
            if stop_loss_dist is not None and stop_loss_dist > 0:
                dist = stop_loss_dist
            elif stop_loss_pct is not None and stop_loss_pct > 0:
                dist = entry_price * stop_loss_pct

            if dist <= 0:
                logger.warning(
                    "Risk Per Trade requires a valid stop_loss_dist or stop_loss_pct. Sizing to 0.0."
                )
                return 0.0
            
            return risk_cap / dist

        elif mode == "kelly":
            if win_rate is None or win_loss_ratio is None or win_loss_ratio <= 0:
                logger.warning("Kelly sizing requires win_rate and win_loss_ratio. Sizing to 0.0.")
                return 0.0
            
            # Kelly formula: f* = p - (1 - p) / b
            k_raw = win_rate - (1.0 - win_rate) / win_loss_ratio
            k_raw = max(0.0, k_raw)  # Never take short/negative Kelly size
            
            k_fraction = k_raw * self.params.kelly_fraction
            return (equity * k_fraction) / entry_price

        elif mode == "vol_target":
            if asset_vol_ann is None or asset_vol_ann <= 0:
                logger.warning("Volatility Target sizing requires asset_vol_ann. Sizing to 0.0.")
                return 0.0
            
            # Vol target weight = Target Vol / Asset Vol
            weight = self.params.target_vol_ann / asset_vol_ann
            return (equity * weight) / entry_price

        elif mode == "atr":
            if atr is None or atr <= 0:
                logger.warning("ATR position sizing requires a valid atr value. Sizing to 0.0.")
                return 0.0
            
            # Stop distance = ATR * multiplier
            dist = atr * self.params.atr_multiplier
            risk_cap = equity * self.params.risk_pct
            return risk_cap / dist

        else:
            logger.error(f"Unknown sizing mode: {self.params.sizing_mode}. Sizing to 0.0.")
            return 0.0

    def update_daily_metrics(self, current_time: datetime, current_equity: float, realized_pnl: float) -> None:
        """
        Manages and tracks the account's daily PnL boundary limits.

        Args:
            current_time: The simulation event timestamp.
            current_equity: The current account equity.
            realized_pnl: Realized PnL change if any.
        """
        event_date = current_time.date()
        
        # Initialize day tracking if not set
        if self.current_day is None:
            self.current_day = event_date
            self.daily_starting_equity = current_equity
            self.daily_realized_pnl = 0.0
            
        elif event_date != self.current_day:
            # Day transition: store old day stats
            self.daily_pnl_history[self.current_day.strftime("%Y-%m-%d")] = self.daily_realized_pnl
            
            # Start new day
            self.current_day = event_date
            self.daily_starting_equity = current_equity
            self.daily_realized_pnl = 0.0

        # Accumulate realized pnl for the current day
        self.daily_realized_pnl += realized_pnl

    def validate_trade_entry(
        self,
        ticker: str,
        quantity: float,
        price: float,
        equity: float,
        active_positions_count: int,
        current_margin_used: float,
        current_portfolio_risk: float,
        timestamp: datetime,
        stop_loss_dist: Optional[float] = None,
        stop_loss_pct: Optional[float] = None,
    ) -> bool:
        """
        Validates if a potential trade execution respects all configured limits.

        Args:
            ticker: The symbol of the asset.
            quantity: Position size to enter.
            price: Entry execution price.
            equity: Current account equity.
            active_positions_count: Current count of active open positions.
            current_margin_used: Current locked margin in the portfolio.
            current_portfolio_risk: Current sum of absolute stop-loss risks.
            timestamp: Event timestamp.
            stop_loss_dist: Stop-loss distance in absolute price (optional).
            stop_loss_pct: Stop-loss percentage (optional).

        Returns:
            True if trade is allowed, False if blocked by risk engine.
        """
        self.trades_evaluated += 1

        # 1. Update peak equity & Drawdown stop check
        self.peak_equity = max(self.peak_equity, equity)
        if self.peak_equity > 0:
            self.current_drawdown = (self.peak_equity - equity) / self.peak_equity
        else:
            self.current_drawdown = 0.0

        if self.current_drawdown >= self.params.max_drawdown_pct:
            self.trading_halted = True

        if self.trading_halted:
            logger.warning(
                f"[RiskEngine] Entry for {ticker} BLOCKED. Trading Halted: "
                f"Drawdown {self.current_drawdown*100:.2f}% exceeds Max Drawdown {self.params.max_drawdown_pct*100:.2f}%."
            )
            self.trades_blocked += 1
            self.block_reasons["max_drawdown"] += 1
            return False

        # 2. Maximum Daily Loss check
        self.update_daily_metrics(timestamp, equity, 0.0)
        daily_loss = equity - self.daily_starting_equity
        if daily_loss < 0:
            loss_pct = abs(daily_loss) / self.daily_starting_equity if self.daily_starting_equity > 0 else 0.0
            self.max_daily_loss_observed = max(self.max_daily_loss_observed, abs(daily_loss))
            if loss_pct >= self.params.max_daily_loss_pct:
                logger.warning(
                    f"[RiskEngine] Entry for {ticker} BLOCKED. Max Daily Loss Hit: "
                    f"Daily Loss ${abs(daily_loss):.2f} ({loss_pct*100:.2f}%) exceeds limit {self.params.max_daily_loss_pct*100:.2f}%."
                )
                self.trades_blocked += 1
                self.block_reasons["max_daily_loss"] += 1
                return False

        # 3. Maximum Concurrent Positions check
        if self.params.max_concurrent_positions is not None and active_positions_count >= self.params.max_concurrent_positions:
            logger.warning(
                f"[RiskEngine] Entry for {ticker} BLOCKED. Max Concurrent Positions: "
                f"Active {active_positions_count} >= Max Limit {self.params.max_concurrent_positions}."
            )
            self.trades_blocked += 1
            self.block_reasons["max_concurrent_positions"] += 1
            return False

        # 4. Maximum Margin Usage check
        trade_value = quantity * price
        required_margin = trade_value / self.params.leverage
        estimated_margin_used = current_margin_used + required_margin
        estimated_margin_usage_pct = estimated_margin_used / equity if equity > 0 else float("inf")
        
        self.max_margin_usage_observed = max(
            self.max_margin_usage_observed, 
            current_margin_used / equity if equity > 0 else 0.0
        )

        if estimated_margin_usage_pct > self.params.max_margin_usage_pct:
            logger.warning(
                f"[RiskEngine] Entry for {ticker} BLOCKED. Max Margin Usage: "
                f"Estimated Margin Usage {estimated_margin_usage_pct*100:.2f}% exceeds limit {self.params.max_margin_usage_pct*100:.2f}%."
            )
            self.trades_blocked += 1
            self.block_reasons["max_margin_usage"] += 1
            return False

        # Update observed margin usage with the proposed trade included
        self.max_margin_usage_observed = max(self.max_margin_usage_observed, estimated_margin_usage_pct)

        # 5. Maximum Portfolio Risk check
        # Calculate proposed trade risk
        trade_risk = 0.0
        if stop_loss_dist is not None and stop_loss_dist > 0:
            trade_risk = quantity * stop_loss_dist
        elif stop_loss_pct is not None and stop_loss_pct > 0:
            trade_risk = quantity * (price * stop_loss_pct)

        estimated_portfolio_risk = current_portfolio_risk + trade_risk
        estimated_portfolio_risk_pct = estimated_portfolio_risk / equity if equity > 0 else float("inf")

        if estimated_portfolio_risk_pct > self.params.max_portfolio_risk_pct:
            logger.warning(
                f"[RiskEngine] Entry for {ticker} BLOCKED. Max Portfolio Risk: "
                f"Estimated Risk ${estimated_portfolio_risk:.2f} ({estimated_portfolio_risk_pct*100:.2f}%) exceeds limit {self.params.max_portfolio_risk_pct*100:.2f}%."
            )
            self.trades_blocked += 1
            self.block_reasons["max_portfolio_risk"] += 1
            return False

        return True

    def generate_report(self, initial_equity: float, ending_equity: float) -> RiskReport:
        """
        Generates a summary RiskReport.
        """
        # Close out the final day if it exists
        if self.current_day is not None:
            self.daily_pnl_history[self.current_day.strftime("%Y-%m-%d")] = self.daily_realized_pnl

        return RiskReport(
            initial_equity=initial_equity,
            ending_equity=ending_equity,
            peak_equity=self.peak_equity,
            max_drawdown_pct=self.current_drawdown,
            total_trades_evaluated=self.trades_evaluated,
            trades_blocked=self.trades_blocked,
            block_reasons=self.block_reasons.copy(),
            max_daily_loss_observed=self.max_daily_loss_observed,
            max_margin_usage_observed=self.max_margin_usage_observed,
            daily_pnl_history=self.daily_pnl_history.copy(),
            trading_halted=self.trading_halted,
        )


# ==============================================================================
# Runnable Example
# ==============================================================================

def run_example() -> None:
    """Demonstrates RiskEngine position sizing and boundary limits."""
    print("--- Running Risk Engine Example ---")

    params = RiskParameters(
        sizing_mode="risk_per_trade",
        risk_pct=0.02,                   # Risk 2% per trade
        max_concurrent_positions=2,      # Limit concurrent positions to 2
        max_margin_usage_pct=0.50,       # Limit margin usage to 50%
        leverage=5.0                     # 5x leverage
    )
    
    risk_engine = RiskEngine(params)
    equity = 10000.0

    # 1. Position Sizing Examples
    # Risk Per Trade sizing
    size_risk = risk_engine.calculate_position_size(
        equity=equity, 
        entry_price=100.0, 
        stop_loss_pct=0.05
    )
    print(f"Risk Per Trade Size (2% risk, 5% stop): {size_risk:.2f} contracts")

    # Change to Kelly Sizing
    risk_engine.params.sizing_mode = "kelly"
    size_kelly = risk_engine.calculate_position_size(
        equity=equity,
        entry_price=100.0,
        win_rate=0.55,
        win_loss_ratio=1.5
    )
    print(f"Kelly Size (55% win rate, 1.5 win/loss ratio, 0.5 fraction): {size_kelly:.2f} contracts")

    # Change back to Risk Per Trade for validation checks
    risk_engine.params.sizing_mode = "risk_per_trade"
    
    # 2. Risk Limit Validation Examples
    t = datetime(2026, 1, 1, 10, 0, 0)
    
    # Check first valid entry
    allowed1 = risk_engine.validate_trade_entry(
        ticker="AAPL",
        quantity=size_risk,
        price=100.0,
        equity=equity,
        active_positions_count=0,
        current_margin_used=0.0,
        current_portfolio_risk=0.0,
        timestamp=t,
        stop_loss_pct=0.05
    )
    print(f"Enter AAPL position allowed? {allowed1}")
    
    # Check entry violating concurrent positions limit (Active positions = 2)
    allowed2 = risk_engine.validate_trade_entry(
        ticker="TSLA",
        quantity=size_risk,
        price=200.0,
        equity=equity,
        active_positions_count=2,
        current_margin_used=2000.0,
        current_portfolio_risk=400.0,
        timestamp=t,
        stop_loss_pct=0.05
    )
    print(f"Enter TSLA position allowed? {allowed2}")

    # Check entry violating margin usage (Needs 8000 margin, limit is 5000)
    allowed3 = risk_engine.validate_trade_entry(
        ticker="BTC",
        quantity=200.0,
        price=200.0,
        equity=equity,
        active_positions_count=1,
        current_margin_used=1000.0,
        current_portfolio_risk=200.0,
        timestamp=t,
        stop_loss_pct=0.05
    )
    print(f"Enter BTC position allowed? {allowed3}")

    # Print summary Risk Report
    report = risk_engine.generate_report(initial_equity=10000.0, ending_equity=9800.0)
    report.print_summary()


if __name__ == "__main__":
    run_example()
